concrete UserConstantsGer of UserConstants = BaseConstantsGer **

-- generated by MkConstants.hs

open
  UtilitiesGer,
  SyntaxGer,
  ParadigmsGer,
  SymbolicGer,
  (L=BaseConstantsLatex),
  Formal

in {
}
