abstract UserConstants = BaseConstants ** {

-- generated by MkConstants.hs

fun denumerable_Adj : Adj ; -- top100
fun polynomial_Noun : Noun ; -- top100
fun degree_Fun : Fun ; -- top100
fun is_root_Relnoun : Relnoun ; -- top100
}
