concrete UserConstantsFre of UserConstants = BaseConstantsFre **

-- generated by MkConstants.hs

open
  UtilitiesFre,
  SyntaxFre,
  ParadigmsFre,
  SymbolicFre,
  (L=BaseConstantsLatex),
  Formal

in {
}
