concrete UserConstantsSwe of UserConstants = BaseConstantsSwe **

-- generated by MkConstants.hs

open
  UtilitiesSwe,
  SyntaxSwe,
  ParadigmsSwe,
  SymbolicSwe,
  (L=BaseConstantsLatex),
  Formal

in {
}
